version: '3.7'
services:
  mysql:
    image: mysql:8-oracle
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=qwerty123

  nodejs:
    build: ./gate-simulator
    image: node:latest
    restart: always
    ports:
      - '9999:9999'